name: run
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run Self hosted Action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Me
        uses: ./ # Uses an action in the root directory
        id: RunMe
        with:
          PLF_END_POINT_URL: "https://pipeline-factory.tools.salt-dev.ws/"
          PLF_API_KEY : ${{ secrets.PLF_API_KEY }}
